### ISSUE TITLE
adicionar documentação do jogo

### ISSUE THREAD

**Issue by ghost** [MarkusLuan/M-Attack-jsWeb#10]
Olá MarkusLuan.

Penso em adicionar documentação do jogo, desse modo alguns desenvolvedores podem extender determinadas funcionalidades ou acrescentar mais recursos. Antes de fazer essa ideia, gostaria de saber se você sente o mesmo ou gostaria de adicionar documentação no jogo ou não.

**atualização:** Você pode encontrar essa implementação aqui: [github/MarkusLuan/M-Attack-jsWeb/pull/12](https://github.com/MarkusLuan/M-Attack-jsWeb/pull/12)

*espero uma resposta sobre essa issue para adicionar um possivelmente pull-request oficial. o que pensa dessa ideia faz sentido ou não?*

**Comment by MarkusLuan** [comment]
Opa, mano. Qual seria a diferença do README.md para a documentação?

E desculpa a demora em dar um feedback, essa semana está bem corrida..... Estou apertado com os estudos e outros projetos que estou fazendo para alguns clientes.

**Comment by MarkusLuan** [comment]
Desculpa a demora mais uma vez.... Mas acabei de aprovar o pull-request.
Valeu meu amigo, um abraço. E que Deus te recompense poderosamente.
