### ISSUE TITLE
novas ideias e sugestões

### ISSUE THREAD

**Issue by codehangen** [MarkusLuan/M-Attack-jsWeb#5]
Olá MarkusLuan.

**1.** Escolher o tipo de fase no jogo. Penso em adicionar mais fases nesse jogo.

**2.** Ao meu ver temos que atualizar a descrição desse repositório.

*antes*
![image](https://user-images.githubusercontent.com/111701513/213787454-b1ceceb7-212f-456b-b73d-cee094f3a2c8.png)

*depois*
![image](https://user-images.githubusercontent.com/111701513/213787853-d45b8214-cd50-4706-baff-f8eaaf52a169.png)

**3.** redesign para o nome do jogo: Alguns motivos para um novo nome do jogo são:
 - Adicionar um nome atraente ao jogo. Com o nome mais atraente, talvez o jogo tenha maior acessibilidade aos desenvolvedores ou usuários de modo geral. E desse modo, por outro lado, em algum sentido comercial possa ter maior destaque também.
 - Geralmente, jogos possuem nomes que são fáceis de lembrar, exemplo: "Runescape", "Jogo da Velha", "Xadrez", "Dungeon&Dragons" etc. Nesse sentido, devemos ter um nome fácil de ser lembrado para que maior parte das pessoas tenha a facilidade em lembrar, associar ou pronunciar. Esse é um segunda boa razão de um novo nome para esse jogo.
 - Outra boa razão é que, além disso, em algum sentido todos os jogos são conhecidos geralmente pelo público. Geralmente em jogos você tem um nome inglês ou algum apelido ao qual os usuários identificam o jogo ou o nome tem haver em algum sentido histórico, social. Um bom exemplo disso, são coisas como: "Futebol", "Basquete" etc que são nomes de jogos que tem sentido histórico e tem haver com aquilo que as pessoas jogam: Futebol vem da palavra football que significa jogar com o pé em tradução literal.
 - Eu gostaria de contribuir com esse repositório e pensei em novo nome do repositório para facilitar que as pessoas tenham em mente o que é o jogo aqui.

*Sugestão de nome*
**space-attack:** espaço em ataque, bem imagino colocar esse nome em inglês já que quando você escreve qualquer jogo ou software em geral o idioma é o inglês, nesse sentido, pensei em um nome em inglês. 

*razão:* Quando joguei seu jogo me lembra bastante um jogo Megamania da Atari.
![image](https://user-images.githubusercontent.com/111701513/213781286-fb8b7bcf-9a6a-464a-94b0-2e30f22b8880.png)

*daí o nome*
![image](https://user-images.githubusercontent.com/111701513/213778932-b16b4f24-e386-484b-a3b6-77e34a69c74f.png)

**markus:** em alguns casos o jogo tem o primeiro nome de quem o criou, pensei em markus.
![image](https://user-images.githubusercontent.com/111701513/213777092-15be7a02-5f9f-450c-907a-24878ec9f7a7.png)

**m2**
![image](https://user-images.githubusercontent.com/111701513/213784423-5f314f7b-2c54-43ed-aaec-721a134a08c2.png)

*O que pensa dessas três ideias?*

**Comment by MarkusLuan** [comment]
Sim sim, boas ideias. Quanto ao nome, estava pensando nisso justamente agora.
Talvez M2 vá confundir com os processadores da Apple na hora de pesquisar, e a Apple é bem chata em relação a isso, eles tem uma fama de jogar processo em tudo que pareça com ela.

Mas eu gostei do space-attack, aí para não ficar tão genérico poderia misturar com a tua ideia e ficar algo como M-Attack, sei lá.

**Comment by MarkusLuan** [comment]
E essa reimaginação dos sprites realmente é algo bacana de se pensar e talvez não seja tão difícil, na verdade dá até para fazer o sprite em tempo de execução (sem ter que criar uma imagem e tal).

**Comment by MarkusLuan** [comment]
aceitei, mano. Valeu.
Agora deixa eu dar uma dica... Deixa o teu gráfico de atividades como publico, pois aumenta teu portifólio (inclusive com essa sua ajuda aqui) e sua networking.

![image](https://user-images.githubusercontent.com/19177386/213797446-cb5c557e-aece-4aea-a93b-68dfdf549022.png)

**Comment by MarkusLuan** [comment]
Show de bola.
Quanto a segunda ideia, eu tinha pensado em tirar o jsWeb, mas para manter mais organizado deixei, já que tenho uns projetos em unity e mobile também.

**Comment by MarkusLuan** [comment]
Beleza, mano. Contribuiu demais, tamo junto.
