### ISSUE TITLE
link de doação para o M-Attack-jsWeb

### ISSUE THREAD

**Issue by ghost** [MarkusLuan/M-Attack-jsWeb#8]
Olá MarkusLuan.

Uma ideia interessante seria adicionar um link de doação no repositório M-Attack-jsWeb. Caso alguém não acesse o site e acesse diretamente esse repositório poderia então aqui enviar uma doação direta.

*Você pode ver essa possível implementação aqui: [github/MarkusLuan/M-Attack-jsWeb/pull/9](https://github.com/MarkusLuan/M-Attack-jsWeb/pull/9)*

Recentemente, adicionei uma pasta chamada `.github` com o arquivo `FUNDING.yml` que é responsável por exibir um botão de doação no repositório do GitHub. Você pode ver mais informações [aqui](https://docs.github.com/pt/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository)

*ideia*
![image](https://user-images.githubusercontent.com/111701513/213807242-5a601f94-8dbd-4805-8fdf-8e16a62ada34.png)

segundo o GitHub é permitido link de doação com o PayPal, não tem opção de pagseguro ou pix. Nesse sentido, é interessante adicionar o link para o site.

para que isso funcione é preciso ativar a opção sponsor
![image](https://user-images.githubusercontent.com/111701513/213809476-bf056921-5418-481f-b7de-162253fb1788.png)

*caso seja aceito você veria algo como*
![image](https://user-images.githubusercontent.com/111701513/213810209-553b18dd-d9b7-4481-952d-18b3a76b7f53.png)

*espero uma resposta sobre essa issue/pull-request. o que pensa dessa ideia faz sentido ou não?*

**Comment by MarkusLuan** [comment]
Opa mano, não sabia que o github tinha isso... Vou só dar uma analisada com mais calma como funciona.

E desculpa a demora em dar um feedback, essa semana está bem corrida..... Estou apertado com os estudos e outros projetos que estou fazendo para alguns clientes.
Mas cheguei a dar uma olhada rápida nos issues e a principio gostei das ideias, só vou precisar analisar depois com mais calma.

Aí deixa só eu resolver o outro projeto e finalizar umas provas, que já analiso.
Um abraço meu amigo e muito obrigado por esse apoio e dedicação.

**Comment by MarkusLuan** [comment]
opa, desculpa a demora.
Acabei de aprovar o pull request, e já estou analisando os outros isues
